#!/usr/bin/env node
'use strict'
/*
|--------------------------------------------------------------------------
|   Running Console Commands
|--------------------------------------------------------------------------
|
|  Here we invoke console commands registered under Ace store.
|
*/
const kernel = require('./bootstrap/kernel')
kernel()